### PR TITLE
Verification of signatures

### PR DESCRIPTION
**Pull request by mmhat**
This commit adds four new functions:
- verifyDetached and verifyDetached'
  Verify a payload using a detached signature.
- verifyPlain and verifyPlain'
  Verify a payload using a plain signature.

### CODE REVIEW

**Comment by rethab** [comment]
Hi, thanks a lot for the PR. Given how little time I currently have for side-projects, would it be okay for to wait until mid November for a proper hackage release?
- Reto

**Comment by rethab** [comment]
Hi @mmhat  thanks for the PR. Would you be so kind and fix the compilation warnings first? Please make sure you rebase against master after that. Thank you. And thanks a lot for your patience.

\- Reto

**Comment by mmhat** [comment]
Hi, I fixed the compilation warnings now. I'm sorry that it took so long.

Regards

**Comment by rethab** [comment]
Thanks a lot man! I have released 0.4.0.0 on hackage!

- Reto

**Pull request merged**
